version: 2.1
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
